import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { ConvexClientProvider } from "@/components/providers/convex-provider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ConvexClientProvider>
        <body className={inter.className}>
          {children}
          <Toaster richColors />
        </body>
      </ConvexClientProvider>
    </html>
  );
}
// # Deployment used by `npx convex dev`
// CONVEX_DEPLOYMENT=dev:proficient-condor-901 # team: jl-calda, project: restorun-biz-app

// NEXT_PUBLIC_CONVEX_URL="https://proficient-condor-901.convex.cloud"

// NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_d2VhbHRoeS1rb2FsYS02NS5jbGVyay5hY2NvdW50cy5kZXYk
// CLERK_SECRET_KEY=sk_test_QJP21FAVHMlHq4xdREGZbuesFd2Z2jtAzmWWXI91ZG
